### ISSUE TITLE
practica libreria DLL

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-salathiel1999#2]
[PracticalibreriaDLL.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-salathiel1999/files/6321512/PracticalibreriaDLL.pdf)

**Comment by Yabin-2021** [comment]
[Evaluación - DLL Calculadora - Irvin Barrera.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-salathiel1999/files/6362833/Evaluacion.-.DLL.Calculadora.-.Irvin.Barrera.pdf)

- Anexo Evaluación DLL Calculadora.
- Puntaje: 18 %.
- Evalúo: Yabin España Aparicio.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
